name: Elixir CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

permissions:
  contents: read

jobs:
  build:

    name: Build and test
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Install OTP and Elixir
          uses: erlef/setup-beam@v1
          with:
            otp-version: ${{ env.otp }}
            elixir-version: ${{ env.elixir }}
      - name: Cache dependencies
          uses: actions/cache@v3
          with:s
            path: |
              deps
              _build
            key: ${{ runner.os }}-elixir-${{ env.elixir }}-otp-${{ env.otp }}-${{ hashFiles('**/mix.lock') }}
      - name: Install dependencies
          run: mix do deps.get, deps.compile
      - name: Run tests
        run: mix test
      - name: Run credo
        run: mix credo
      - name: Check formatting
        run: mix format --check-formatted
